# Generated by Django 5.2.11 on 2026-02-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('cod', models.FloatField(blank=True, null=True)),
                ('chlorides', models.FloatField(blank=True, null=True)),
                ('suspended_solids', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='sim', max_length=30)),
                ('compliance', models.CharField(default='UNKNOWN', max_length=20)),
                ('anomaly_flag', models.BooleanField(default=False)),
                ('deviation_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='STPReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('cod', models.FloatField(blank=True, null=True)),
                ('chlorides', models.FloatField(blank=True, null=True)),
                ('suspended_solids', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='sim', max_length=30)),
                ('compliance', models.CharField(default='UNKNOWN', max_length=20)),
                ('anomaly_flag', models.BooleanField(default=False)),
                ('deviation_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
    ]
